server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
  redis:
    host: localhost
    port: 6379
logging:
  level:
    com.james.dao: debug